## Import files (Colors,Etc)
import:
  - ~/.config/alacritty/night/colors.yml

## Set environment variables
env:
  TERM: xterm-256color

## Terminal window settings
window:
  opacity: 1.0
  padding:
    x: 25
    y: 25

## Font
font:
  normal:
    family: Iosevka Nerd Font Mono
    style: Regular

  bold:
    family: Iosevka Nerd Font Mono
    style: Bold

  italic:
    family: Iosevka Nerd Font Mono
    style: Italic

  bold_italic:
    family: Iosevka Nerd Font Mono
    style: Bold Italic

  size: 10

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

# Class
class:
  instance: Alacritty
  general: Alacritty

# Scrolling
scrolling:
  history: 10000
  multiplier: 3

# Visual
visual_bell:
  animation: EaseOutExpo
  duration: 0.5
  color: "#ffffff"

# Selection
selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

# Cursor
cursor:
  style: 'Underline'

# Shell
shell:
  program: /usr/bin/zsh

# Mouse
mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true

# Global Configuration
live_config_reload: true
draw_bold_text_with_bright_colors: true
