#!/usr/bin/bash

user=$(users) && sudo chown $user:$user /usr/bin/autoawesome && sudo chown -R $user:$user /home/$user/AutoAwesome && sudo chown -R $user:$user /home/$user/.local && kitty sh -c "sudo autoawesome"
